version: "3.9"
services:
  indiekit:
    container_name: indiekit-app
    image: kyank/indiekit
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://indiekit:replaceme@mongo
      - PASSWORD_SECRET=replaceme
      - SECRET=replaceme
      - GITHUB_TOKEN=replaceme
      - MASTODON_ACCESS_TOKEN=replaceme
  mongo:
    container_name: indiekit-mongo
    image: mongo:4 # 5+ requires AVX instruction set not supported on Synology 1019+
    restart: always
    volumes:
      - indiekit-mongo-data:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=indiekit
      - MONGO_INITDB_ROOT_PASSWORD=replaceme

volumes:
  indiekit-mongo-data:
    external: true
