version: "3.9"
services:
  indiekit:
    container_name: indiekit-app
    image: kyank/indiekit
    restart: always
    build: .
    ports:
      - "${HTTP_PORT:-3000}:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo
      - PASSWORD_SECRET
      - SECRET
      - GITHUB_TOKEN
      - MASTODON_ACCESS_TOKEN
  mongo:
    container_name: indiekit-mongo
    image: mongo:4 # 5+ requires AVX instruction set not supported on Synology 1019+
    restart: always
    volumes:
      - indiekit-mongo-data:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

volumes:
  indiekit-mongo-data:
    external: true
